### ISSUE TITLE
RuntimeError: More than 4 outlier pixels

### ISSUE THREAD

**Issue by xk42** [Seeed-Studio/Seeed_Python_MLX9064x#3]
I'm having some issues with the MLX90640. This is running on pi4 raspbian 4.19.97-v7l+

```
root@pi4:~/seeed_ircamera# i2cdump -y 3 0x33 i
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f    0123456789abcdef
00: 00 00 00 a2 79 9f 00 00 20 61 00 04 03 20 03 e0    ...?y?.. a.?? ??
10: 07 22 88 b0 61 87 04 8d 00 00 fc 7f 00 00 00 00    ?"??a???..??....
20: 00 00 00 a2 79 9f 00 00 20 61 00 04 03 20 03 e0    ...?y?.. a.?? ??
30: 07 22 88 b0 61 87 04 8d 00 00 fc 7f 00 00 00 00    ?"??a???..??....
40: 00 00 00 a2 79 9f 00 00 20 61 00 04 03 20 03 e0    ...?y?.. a.?? ??
50: 07 22 88 b0 61 87 04 8d 00 00 fc 7f 00 00 00 00    ?"??a???..??....
60: 00 00 00 a2 79 9f 00 00 20 61 00 04 03 20 03 e0    ...?y?.. a.?? ??
70: 07 22 88 b0 61 87 04 8d 00 00 fc 7f 00 00 00 00    ?"??a???..??....
80: 00 00 00 a2 79 9f 00 00 20 61 00 04 03 20 03 e0    ...?y?.. a.?? ??
90: 07 22 88 b0 61 87 04 8d 00 00 fc 7f 00 00 00 00    ?"??a???..??....
a0: 00 00 00 a2 79 9f 00 00 20 61 00 04 03 20 03 e0    ...?y?.. a.?? ??
b0: 07 22 88 b0 61 87 04 8d 00 00 fc 7f 00 00 00 00    ?"??a???..??....
c0: 00 00 00 a2 79 9f 00 00 20 61 00 04 03 20 03 e0    ...?y?.. a.?? ??
d0: 07 22 88 b0 61 87 04 8d 00 00 fc 7f 00 00 00 00    ?"??a???..??....
e0: 00 00 00 a2 79 9f 00 00 20 61 00 04 03 20 03 e0    ...?y?.. a.?? ??
f0: 07 22 88 b0 61 87 04 8d 00 00 fc 7f 00 00 00 00    ?"??a???..??....
```

    root@pi4:~# i2cdetect -y 1
         0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
    00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
    10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
    20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
    30: -- -- -- 33 -- -- -- -- -- -- -- -- -- -- -- -- 
    40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
    50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
    60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
    70: -- -- -- -- -- -- -- --     

```
root@pi4:~/seeed_ircamera# python3 seeed_python_ircamera.py 
Traceback (most recent call last):
  File "seeed_python_ircamera.py", line 322, in <module>
    run()
  File "seeed_python_ircamera.py", line 316, in run
    dataThread = DataReader(port)
  File "seeed_python_ircamera.py", line 66, in __init__
    self.dataHandle = seeed_mlx90640.grove_mxl90640()
  File "/usr/local/lib/python3.7/dist-packages/seeed_mlx90640.py", line 61, in __init__
    self._ExtractParameters()
  File "/usr/local/lib/python3.7/dist-packages/seeed_mlx90640.py", line 289, in _ExtractParameters
    self._ExtractDeviatingPixels()
  File "/usr/local/lib/python3.7/dist-packages/seeed_mlx90640.py", line 680, in _ExtractDeviatingPixels
    raise RuntimeError("More than 4 outlier pixels")
RuntimeError: More than 4 outlier pixels```

```
root@pi4:~/seeed_ircamera# grep i2c /boot/config.txt
#dtparam=i2c_arm=on
dtparam=i2c_arm=on,i2c_arm_baudrate=400000
```

**Comment by Pillar1989** [comment]
@xk42 The relevant exception code handling should be added here

**Comment by albydnc** [comment]
Same issue here
