### ISSUE TITLE
Bus Error: How can i define the bus?

### ISSUE THREAD

**Issue by mwkldeveloper** [Seeed-Studio/Seeed_Python_MLX9064x#7]
Hi

I got below Error:

```
Traceback (most recent call last):
  File "app.py", line 2, in <module>
    mlx = seeed_mlx90640.grove_mxl90640()
  File "/home/pi/.local/lib/python3.7/site-packages/seeed_mlx90640.py", line 56, in __init__
    self.bus = Bus()
  File "/home/pi/.local/lib/python3.7/site-packages/grove/i2c.py", line 59, in __init__
    bus = rev_to_bus[rev]
KeyError: 0
```

I have 2 i2c*
/dev/i2c-1  /dev/i2c-3

I found that in seeed_mlx90640 line 56, define the Bus is None, so the ic2 get GPIO.RPI_REVISION as the bus which is 0
But i don't have 0 , How can i define the bus to 1?
```
    def __init__(self,address=0x33):
        self.bus = Bus()
        self.addr = address
        self.refresh_rate = RefreshRate.REFRESH_0_5_HZ 
        self._I2CReadWords(0x2400, eeData)
        # print(eeData)
        self._ExtractParameters()
```

**Comment by Hansen0314** [comment]
Hi there:
   if you want to modify it .maybe you can be using self.bus = Bus(1).
