### ISSUE TITLE
Not able to read from the thermal camera

### ISSUE THREAD

**Issue by dsampangi** [Seeed-Studio/Seeed_Python_MLX9064x#8]
pi@raspberrypi:~/Seeed_Python_MLX9064x/examples $ sudo python3 BasicReadings.py 
Traceback (most recent call last):
  File "BasicReadings.py", line 22, in <module>
    main()
  File "BasicReadings.py", line 9, in main
    mlx = seeed_mlx9064x.grove_mxl90640()
  File "/usr/local/lib/python3.7/dist-packages/seeed_mlx9064x.py", line 90, in __init__
    self._ExtractParameters()
  File "/usr/local/lib/python3.7/dist-packages/seeed_mlx9064x.py", line 318, in _ExtractParameters
    self._ExtractDeviatingPixels()
  File "/usr/local/lib/python3.7/dist-packages/seeed_mlx9064x.py", line 709, in _ExtractDeviatingPixels
    raise RuntimeError("More than 4 outlier pixels")
RuntimeError: More than 4 outlier pixels

**Comment by is-qian** [comment]
Currently, there is no update on this aspect. You can try modifying GrovePi to run it. If you get good results, you can submit a pull request to us for testing.

**Comment by is-qian** [comment]
The issue is caused by your use of MLX90641, whereas MLX90640 is used by default in BasicReadings.py. You need to change MLX90640 to MLX90641 [here](https://github.com/Seeed-Studio/Seeed_Python_MLX9064x/blob/master/examples/BasicReadings.py#L3). If it still doesn't work, please reopen this issue.
